# Generated by Django 5.1.6 on 2025-02-06 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('name', models.TextField()),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('pw', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='apis',
            fields=[
                ('key', models.TextField()),
                ('api_id', models.AutoField(primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tubeboxApp.user')),
            ],
        ),
    ]
